general:
  gitSshKeyCredentialsId: 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

steps:
  cloudFoundryDeploy:
    deployTool: 'cfdeploy'
    cloudFoundry:
      org: 'SAP_<MyProject>'
      space: '<My Project>-<dev>'
      credentialsId: 'cfdeploy'
  newmanExecute:
    newmanCollection: 'myNewmanCollection.file'
    newmanEnvironment: 'myNewmanEnvironment'
    newmanGlobals: 'myNewmanGlobals'