general:
  gitSshKeyCredentialsId: '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'
steps:
  cloudFoundryDeploy:
    deployTool: 'mta'
    cloudFoundry:
      org: 'SAP_<MyProject>'
      space: '<My Project>-<dev>'
      credentialsId: 'cfdeploy'
  newmanExecute:
    newmanCollection: 'myNewmanCollection.file'
    newmanEnvironment: 'myNewmanEnvironment'
    newmanGlobals: 'myNewmanGlobals'




# general:
#   buildTool: "mta"
# service:
#   buildToolVersion: "MBTJ8N14"
# stages:
#   Build:
#     npmExecuteLint: false
#   Additional Unit Tests:
#     npmExecuteScripts: false
#     karmaExecuteTests: false
#   Malware Scan:
#     malwareExecuteScan: true
#   Acceptance:
#     cloudFoundryDeploy: true
#     cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
#     cfOrg: "SAP_<MyProject>"
#     cfSpace: "<My Project>-<dev>"
#     cfCredentialsId: "cfdeploy"
#     npmExecuteEndToEndTests: false
#   Compliance:
#     sonarExecuteScan: false
#   Release:
#     cloudFoundryDeploy: true
#     cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
#     cfOrg: "SAP_<MyProject>"
#     cfSpace: "<My Project>-<dev>"
#     cfCredentialsId: "cfdeploy"
#     tmsUpload: false
# steps:
#   artifactPrepareVersion:
#     versioningType: "cloud_noTag"
#   cloudFoundryDeploy:
#     mtaDeployParameters: "-f --version-rule ALL"





# general:
#   gitSshKeyCredentialsId: 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

# steps:
#   cloudFoundryDeploy:
#     deployTool: 'mta'
#     cloudFoundry:
#       org: 'SAP_<MyProject>'
#       space: '<My Project>-<dev>'
#       credentialsId: 'cfdeploy'

# hooks:
#   splunk:
#     dsn: 'YOUR SPLUNK HEC ENDPOINT'
#     token: 'YOURTOKEN'
#     index: 'SPLUNK INDEX'
#     sendLogs: true
